FROM node:22-alpine as build
WORKDIR /app

COPY package*.json ./
RUN npm install

ARG VITE_APP_BACKEND_URL
ARG VITE_API_KEY
ENV VITE_APP_BACKEND_URL=$VITE_APP_BACKEND_URL
ENV VITE_API_KEY=$VITE_API_KEY

COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
